# action.yml
name: Create a github.go file
description: Create a github.go file containing GitHub release information.
author: support@senzing.com

inputs:
  file:
    description: "The file to create. Default: cmd/github.go"
    required: false
    default: cmd/github.go
  package:
    description: "The package name for the package statement. Default: cmd"
    required: false
    default: cmd
  actor:
    description: "Optional GitHub actor for signed commits. Must correspond to the noreply email used to create the GPG key."
    required: false
  github_token:
    description: "GitHub token for git push authentication."
    required: false
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - name: run file
      run: ${{ github.action_path }}/entrypoint.sh
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        INPUT_FILE: ${{ inputs.file }}
        INPUT_PACKAGE: ${{ inputs.package }}
        INPUT_ACTOR: ${{ inputs.actor }}

branding:
  icon: git-pull-request
  color: red
